Feature/multi countries
BilelJegham/epidemic-simulator-front pull request #7
Opened 2020-03-31 13:37 UTC by BilelJegham

2020-04-05 13:45 UTC, BilelJegham commented
@RemiTheWarrior I think it's OK, I let you check.

https://epidemic-simulator-git-feature-multi-countries.bileljegham.now.sh/#/

2020-04-05 19:08 UTC, RemiTheWarrior commented
Is there a way to order the legend by country ?
![image](https://user-images.githubusercontent.com/40028739/78507650-a3c05980-7781-11ea-9636-ec3c3abcbb35.png)

2020-04-05 19:10 UTC, RemiTheWarrior commented
![image](https://user-images.githubusercontent.com/40028739/78507671-d0747100-7781-11ea-9994-ba368879935a.png)
Concerning the default behaviour, I can't see the series deaths - France (no simu).

2020-04-05 19:12 UTC, RemiTheWarrior commented
![image](https://user-images.githubusercontent.com/40028739/78507699-fd288880-7781-11ea-921d-40a7706136ad.png)
Is it possible to ensure the default display (infected + deaths, sim + actual data) ?

Way to reproduce:
- Set France
- Set UK
- click on "display count date"

2020-04-07 12:10 UTC, BilelJegham commented
I think it's related to issue #8 : problem of cache browser 

Try with `ctrl+F5`.

2020-04-07 12:17 UTC, RemiTheWarrior commented
okay then, what about sorting the legend by country ?

2020-04-07 12:39 UTC, RemiTheWarrior commented
![image](https://user-images.githubusercontent.com/40028739/78670137-9a4c0400-78dd-11ea-8303-6f6f02ee9bd7.png)
Is it possible to keep points for actual data ?

2020-04-07 12:45 UTC, RemiTheWarrior commented
![image](https://user-images.githubusercontent.com/40028739/78670610-54437000-78de-11ea-9913-f1b7d67e74ef.png)
It still seems to have some bugs when comparing countries with "display count date"

2020-04-15 12:02 UTC, RemDelaporteMathurin requested changes

2020-04-15 12:02 UTC, RemiTheWarrior commented on src/views/AccueilPage.vue
> +         <p class="text-center"><md-switch v-model="number" class="md-primary">Compare country</md-switch><br/>
`Compare country` should be `Compare countries`

2020-04-16 16:00 UTC, merged